#version: '3.8'

services:
  # MinIO service - provides S3 compatible object storage
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z 
    container_name: minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Abcd1234
      MINIO_DOMAIN: minio
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      minio_network:
        aliases:
          - warehouse.minio

  rest:
    image: tabulario/iceberg-rest:1.6.0
    container_name: rest
    networks:
      minio_network:
        aliases:
          - iceberg-rest.minio
    ports:
      - "8181:8181"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://iceberg/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://localhost:9000


  jobmanager:
    image: flink:1.20-paimon-1.2.0
    #container_name: flink-jobmanager
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 2048m
        parallelism.default: 1
    ports:
      - "28081:8081"
    command: jobmanager
    volumes:
      - ./job:/opt/flink/job
    deploy:
      replicas: 1

  taskmanager:
    image: flink:1.20-paimon-1.2.0
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        taskmanager.memory.process.size: 4096m
        taskmanager.memory.framework.off-heap.size: 256m
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2

  client:
    image: flink:1.20-paimon-1.2.0
    #container_name: flink-client
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
    depends_on:
      - jobmanager
    command: tail -f /dev/null
    volumes:
      - ./job:/opt/flink/job


networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:

